name = "cogito"
license = "MIT"
licenselink = "https://github.com/slashformotion/cogito/blob/master/LICENSE"
description = "A hackable hugo theme for personal blog. Forked from cactus created by @monkeyWzr."
homepage = "https://github.com/slashformotion/cogito"
demosite = "https://slashformotion.github.io/cogito/"
tags = ["blog", "responsive", "personal"]
features = ["mathjax", "customizable", "color"]
min_version = "0.83"

# If the theme has a single author
[author]
    name = "Slashformotion"
    homepage = "https://github.com/slashformotion"

# If porting an existing theme
[original]
    author = "呉澤冉"
    homepage = "https://github.com/monkeyWzr"
    repo = "https://github.com/monkeyWzr/hugo-theme-cactus"